[toolchain]
package_manager = "npm"
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
merke_airdrop = "Dpjs4ihZc6T9Y6mBfgDcmRavoFysLRDpdW5fezbxGZ33"
vesting = "8bSvkfYPuNqNRSSZzPD62H1dDPrACYPLLQitkYWVs75q"
converter = "87ReJzgQU1KDbRWRtGC1DTtxUZ6dE3MkcEx2a37fFySr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
# cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
claim = "npm run claim --"
init = "npm run init:distributor --"
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
